### ISSUE TITLE
Does BehaviorSubject need to be closed?

### ISSUE THREAD

**Issue by rajkar86** [filiph/hn_app#4]
New to dart/flutter. I apologize for creating a PR to ask questions.
Are the close() methods of HackerNewsBloc/PrefsBloc ever executed actually?
Regardless, is it necessary to close BehaviorSubjects in this use case?

**Comment by TheJulianJES** [comment]
I *think* that they mentioned that it's not really needed to close it in this case, as it's needed for the whole app lifecycle.

**Comment by filiph** [comment]
Sorry for the delayed response! I probably unwatched this repo by mistake 🤦‍♂ .

Anyway. Since the blocs are needed for the whole duration of the app (there is no time when they're not needed), they aren't disposed of.

That said, for testing, it would be better to dispose of the blocs, and therefore close the BehaviorSubjects. So while the app itself doesn't leak, the architecture is far from perfect in this respect.

I'm going to close this issue since we moved to Provider for educational purposes, so there are no more BehaviorSubjects in the app.

Cheers!
